lngStrings={
'ABPtext':	{'en':'Annual (A), biennial (B) and perennial (P) plants.', 'se':'Årliga (A), tvååriga (B) och fleråriga (P) växter.', 'ru':'Однолетние (А), двухлетние (B) и многолетние (P) растения.' },
'About REALS':{'en':'About REALS',							'se':'Om REALS',							'ru':'О проэкте REALS'},
'EdibName':	{'en':'Edible plants',							'se':'Ätbara växter',						'ru':'Съедобные растения'},
'EdibText':	{'en':'Nature has many tasty foods',			'se':'Naturen har många godsaker',			'ru':'У природы есть много вкусного'},
'EdibUse':	{'en':'For food',								'se':'Som mat',								'ru':'Как приготовить'},
'Favourites':{'en':'My Favourites',							'se':'Mina favoriter',						'ru':'Мои избранные'},
'heading':	{'en':'Wild, edible plants',					'se':'Vilda, ätbara växter',				'ru':'Дикие, съедобные растения'},
'intro1':	{'en':'The old, revered knowledge of edible plants and natural medicines is getting forgotten.',
			 'se':'Den gamla, vördade kunskapen om ätbara plantor och naturliga mediciner håller på att falla i glömska.',
			 'ru':'Древние, чтимые знания о съедобных растениях и природной медицине впадают в забвение.'},
'intro2.1':	{'en':'But with the help of the ',
			 'se':'Men med hjälp av ',
			 'ru':'Но с помощью базы данных от '},
'intro2.2':	{'en':' database with 7000+ records of beneficial plants, the knowledge stays intact for generations to come.',
			 'se':'-databasen med över 7000 nedskrivna välgörande plantor kan kunskapen hållas vid liv i generationer.',
			 'ru':' с более 7000 записями полезных растений, знания переносятся будущим поколениям.'},
'intro3': 	{'en':'The list below is a subset of this large database, depicting plants growing in the Nordic countries.',
			 'se':'Nedanstående lista är en del av denna stora databas, som skildrar växter som växer i de nordiska länderna',
			 'ru':'Нижеоглашенный список - часть этой большой базы данных, который отображает растения растущие в Странах Северных Европы.'},
'intro4.1': {'en':'The list is under continued dialogue within the ',
			 'se':'Listan är under ständig dialog inom ',
			 'ru':'Список в состоянии постоянных переговоров в проэкте '},
'intro4.2': {'en':' project and is compiled by Alexandra Kuliasova (REEN Russia), Antonina Kuliasova (REEN Russia) and Emilia Rekestad',
			 'se':'-projektet och är sammanställd av Alexandra Kuliasova (REEN Russia), Antonina Kuliasova (REEN Russia) och Emilia Rekestad',
			 'ru':' и составлен Александрой Кулясовой (РЕЕН Россия), Антониной Кулясовой (РЕЕН Россия) и Эмилией Рекестад'},
'PermacultureSweden':{'en':'Permaculture Sweden', 'se':'Permakultur Sverige', 'ru':'Пермакультура Швеции'},
'Language':	{'en':'Language',								'se':'Språk',								'ru':'Язык'},
'MediUse':	{'en':'For medicine',							'se':'Som medicin',							'ru':'Лекарство'},
'MediName':	{'en':'Medicinal plants',						'se':'Medicinväxter',						'ru':'Лекарственные растения'},
'MediText':	{'en':'Mother Nature is always there for you!',	'se':'Moder Jord finns alltid där för dig',	'ru':'Природа-мать всегда с тобой'},
'Section':	{'en':'Section',								'se':'Del',									'ru':'Раздел'},
'WildName':	{'en':'Wild plants',							'se':'Vilda växter',						'ru':'Дикие растения'},
'WildText':	{'en':'Make use of them!',						'se':'Använd dem!',							'ru':'Используй их!'}
};