lngLanguages=['en','se','ru','rut'];
lngStrings={
'about1':	{'en':'REALS ran between September 2013 and August 2016. It was a creative forum and platform for diverse conversations, practical activities, exchange of experience and knowledge, new projects, long lasting friendship and - not the least - dissemination of future solutions for a healthy planet.',
			 'se':'REALS varade mellan september 2013 och augusti 2016. Det var ett kreativt forum och plattform för en mångfald av konversationer, praktiska aktiviteter, utbyte av erfarenhet och kunskap, nya projekt, långvarig vänskap och - inte minst - spridning av framtida lösningar för en frisk planet.',
			 'ru':'REALS длился с сентября 2013 по август 2016. Это был творческий форум и площадка для разнообразных переговоров, практических мероприятий, обмена опыта и знаний, новых проектов, долговечной дружбы и, конечно же, для распространения будущих решений для здоровой планеты.'},
'about2':	{'en':'The name stands for Resilient and Ecological Approaches for Living Sustainably. Read more',
			 'se':'Namnet står för Resilienta och ekologiska tillvägagångssätt för hållbart levande (en: Resilient and Ecological Approaches for Living Sustainably). Läs mer',
			 'ru':'Название означает Упругие и экологические подходы к устойчивому образу жизни (англ: Resilient and Ecological Approaches for Living Sustainably). Читайте далее'},
'about3':	{'en':'REALS is financed', 						'se':'REALS sponsras', 						'ru':'Проект REALS спонсируется'},
'ABPtext':	{'en':'Annual (A), biennial (B) and perennial (P) plants.', 'se':'Årliga (A), tvååriga (B) och fleråriga (P) växter.', 'ru':'Однолетние (А), двухлетние (B) и многолетние (P) растения.' },
'About REALS':{'en':'About REALS',							'se':'Om REALS',							'ru':'О проэкте REALS'},
'byAntonFjodorov': {'en':'Anton Fjodorov',					'se':'Anton Fjodorov',						'ru':'Федоровым Антоном'},
'by the Swedish Institute':{'en':'by the Swedish Institute','se':'av Svenska institutet',				'ru':'Шведским институтом'},
'QuickInfo': {'en':'Quick translation',						'se':'Snabböversättning',					'ru':'Быстрый перевод'},
'Categories': {'en':'Categories', 'se':'Kategorier', 'ru':'Категории'},
'cookie1':	{'en':'This site uses cookies.',				'se':'Sidan använder kakor.',				'ru':'Сайт использует куки.'},
'cookie2':	{'en':'Cookies are used to store your favourite plants and whether you accepted this cookie policy.',
			 'se':'Kakor används för att lagra dina favoritmarkerade plantor och om du accepterat denna policy.',
			 'ru':'Куки хранят ваши избранные растения, а так же ваше согласие по поводу данных куки.'},
'EdibName':	{'en':'Edible plants',							'se':'Ätbara växter',						'ru':'Съедобные растения'},
'EdibText':	{'en':'Nature has many tasty foods',			'se':'Naturen har många godsaker',			'ru':'У природы есть много вкусного'},
'EdibUse':	{'en':'For food',								'se':'Som mat',								'ru':'Как приготовить'},
'Favourites':{'en':'My Favourites',							'se':'Mina favoriter',						'ru':'Мои избранные'},
'favsNoitems':{'en':'You have not marked any plants as favourite yet. Do it by clicking on the heart symbol on a plant.',
			   'se':'Du har inte favoritmarkerat några växter än. Gör det genom att klicka på hjärtat vid varje växt.',
			   'ru':'У вас еще нет избранных растений. Нажмите на сердечко на растении, чтобы выбрать его.'},
'favsHasitems':{'en':'Click on an item to quickly find it on the website.',
			   'se':'Klicka på en växt här under för att hitta den snabbt på sidan.',
			   'ru':'Кликните на одно из растений ниже, чтобы быстро найти его на странице.'},
'heading':	{'en':'Wild, edible plants',					'se':'Vilda, ätbara växter',				'ru':'Дикие, съедобные растения'},
'headerMedi':{'en':'Medicinal and edible plants in the Nordic region',
			  'se':'Medicinska och ätbara växter i den nordiska regionen',
			  'ru':'Лечебные и съедобные травы в северном регионе'},
'IAccept':	{'en':'I accept',								'se':'Acceptera',							'ru':'Принять'},
'intro1':	{'en':'The revered old knowledge about edible plants and natural medicines is getting forgotten.',
			 'se':'Den vördade gamla kunskapen om ätbara plantor och naturliga mediciner håller på att falla i glömska.',
			 'ru':'Чтимые древние знания о съедобных растениях и природной медицине впадают в забвение.'},
'intro2.1':	{'en':'But with the help of the ',
			 'se':'Men med hjälp av ',
			 'ru':'Но с помощью базы данных от '},
'intro2.2':	{'en':' database with 7000+ records of beneficial plants, the knowledge stays intact for generations to come.',
			 'se':'-databasen med över 7000 nedskrivna välgörande plantor kan kunskapen hållas vid liv i generationer.',
			 'ru':' с более 7000 записями полезных растений, знания переносятся будущим поколениям.'},
'intro3': 	{'en':'The list below is a subset of this large database, depicting plants growing in the Nordic countries.',
			 'se':'Nedanstående lista är en del av denna stora databas, som skildrar växter som växer i de nordiska länderna.',
			 'ru':'Нижеоглашенный список - часть этой большой базы данных, который отображает растения растущие в Странах Северных Европы.'},
'intro4.1': {'en':'The list is under continued dialogue within the ',
			 'se':'Listan är under ständig dialog inom ',
			 'ru':'Список в состоянии постоянных переговоров в проэкте '},
'intro4.2': {'en':' project and is compiled by Alexandra Kuliasova (REEN Russia), Antonina Kuliasova (REEN Russia) and Emilia Rekestad',
			 'se':'-projektet och är sammanställd av Alexandra Kuliasova (REEN Russia), Antonina Kuliasova (REEN Russia) och Emilia Rekestad',
			 'ru':' и составлен Александрой Кулясовой (РЕЕН Россия), Антониной Кулясовой (РЕЕН Россия) и Эмилией Рекестад'},
'intro4.3': {'en':'Website by',								'se':'Sajt av',								'ru':'Сайт создан'},
'Language':	{'en':'Language',								'se':'Språk',								'ru':'Язык'},
'Lifespan':	{'en':'Lifespan', 'se':'Livslängd', 'ru':'Продолжительность жизни'},
'(A)nnual':	{'en':'(A): Annual', 'se':'(A): Ettårig', 'ru':'(A): Однолетнее'},
'(B)iennial':{'en':'(B): Biennial', 'se':'(B): Tvåårig', 'ru':'(B): Двулетнее'},
'(P)erennial':{'en':'(P): Perennial', 'se':'(P): Flerårig', 'ru':'(P): Многолетнее'},
'OkIAccept':{'en':'Ok, I accept',							'se':'Ok, acceptera',						'ru':'Хорошо, принять'},
'on the REALS website':{'en':'on the REALS website', 		'se':'på REALS-hemsidan', 					'ru':'на странице REALS'},
'MediUse':	{'en':'For medicine',							'se':'Som medicin',							'ru':'Лекарство'},
'MediName':	{'en':'Medicinal plants',						'se':'Medicinväxter',						'ru':'Лекарственные растения'},
'MediText':	{'en':'Mother Nature is always there for you!',	'se':'Moder Jord finns alltid där för dig',	'ru':'Природа-мать всегда с тобой'},
'PermacultureSweden':{'en':'Permaculture Sweden',			'se':'Permakultur Sverige',					'ru':'Пермакультура Швеции'},
'pfaf':		{'en':'Plants For a Future',
			 'se':'Plants For a Future (Växter för framtiden)',
			 'ru':'Plants For a Future (Растения для будущего)'},
'ReadMore':	{'en':'Read more',								'se':'Läs mer',								'ru':'Подробнее'},
'Section':	{'en':'Section',								'se':'Del',									'ru':'Раздел'},
'Tothetop':	{'en':'To the top',								'se':'Till toppen',							'ru':'Наверх'},
'WildName':	{'en':'Wild plants',							'se':'Vilda växter',						'ru':'Дикие растения'},
'WildText':	{'en':'Make use of them!',						'se':'Använd dem!',							'ru':'Используй их!'}
};